<?php

namespace ContainerIM1q2C1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I3NsxiZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i3NsxiZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i3NsxiZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'prestation' => ['privates', '.errored..service_locator.i3NsxiZ.App\\Entity\\Prestation', NULL, 'Cannot autowire service ".service_locator.i3NsxiZ": it references class "App\\Entity\\Prestation" but no such service exists.'],
        ], [
            'prestation' => 'App\\Entity\\Prestation',
        ]);
    }
}
