<?php

namespace ContainerIM1q2C1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrestationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.i3NsxiZ.App\Entity\Prestation' shared service.
     *
     * @return \App\Entity\Prestation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.i3NsxiZ": it references class "App\\Entity\\Prestation" but no such service exists.');
    }
}
