<?php

namespace ContainerMvhfkx6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PzLWnRAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pzLWnRA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pzLWnRA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AvisController::createAvis' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\AvisController::index' => ['privates', '.service_locator.uRm8g0q', 'get_ServiceLocator_URm8g0qService', true],
            'App\\Controller\\AvisController::show' => ['privates', '.service_locator.XxYNAyR', 'get_ServiceLocator_XxYNAyRService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\PresentationController::deletePresentation' => ['privates', '.service_locator._NWIuTN', 'get_ServiceLocator_NWIuTNService', true],
            'App\\Controller\\PresentationController::formPresentation' => ['privates', '.service_locator.jvgsY1u', 'get_ServiceLocator_JvgsY1uService', true],
            'App\\Controller\\PrestationController::delete' => ['privates', '.service_locator.i3NsxiZ', 'get_ServiceLocator_I3NsxiZService', true],
            'App\\Controller\\PrestationController::form' => ['privates', '.service_locator.Pn8ZKjs', 'get_ServiceLocator_Pn8ZKjsService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AvisController:createAvis' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\AvisController:index' => ['privates', '.service_locator.uRm8g0q', 'get_ServiceLocator_URm8g0qService', true],
            'App\\Controller\\AvisController:show' => ['privates', '.service_locator.XxYNAyR', 'get_ServiceLocator_XxYNAyRService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\PresentationController:deletePresentation' => ['privates', '.service_locator._NWIuTN', 'get_ServiceLocator_NWIuTNService', true],
            'App\\Controller\\PresentationController:formPresentation' => ['privates', '.service_locator.jvgsY1u', 'get_ServiceLocator_JvgsY1uService', true],
            'App\\Controller\\PrestationController:delete' => ['privates', '.service_locator.i3NsxiZ', 'get_ServiceLocator_I3NsxiZService', true],
            'App\\Controller\\PrestationController:form' => ['privates', '.service_locator.Pn8ZKjs', 'get_ServiceLocator_Pn8ZKjsService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AvisController::createAvis' => '?',
            'App\\Controller\\AvisController::index' => '?',
            'App\\Controller\\AvisController::show' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\PresentationController::deletePresentation' => '?',
            'App\\Controller\\PresentationController::formPresentation' => '?',
            'App\\Controller\\PrestationController::delete' => '?',
            'App\\Controller\\PrestationController::form' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AvisController:createAvis' => '?',
            'App\\Controller\\AvisController:index' => '?',
            'App\\Controller\\AvisController:show' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\PresentationController:deletePresentation' => '?',
            'App\\Controller\\PresentationController:formPresentation' => '?',
            'App\\Controller\\PrestationController:delete' => '?',
            'App\\Controller\\PrestationController:form' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
