<?php

namespace ContainerMvhfkx6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NWIuTNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._NWIuTN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._NWIuTN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'presentation' => ['privates', '.errored..service_locator._NWIuTN.App\\Entity\\Present', NULL, 'Cannot autowire service ".service_locator._NWIuTN": it references class "App\\Entity\\Present" but no such service exists.'],
        ], [
            'presentation' => 'App\\Entity\\Present',
        ]);
    }
}
