<?php

namespace ContainerMvhfkx6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvisService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XxYNAyR.App\Entity\Avis' shared service.
     *
     * @return \App\Entity\Avis
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.XxYNAyR": it references class "App\\Entity\\Avis" but no such service exists.');
    }
}
