<?php

namespace ContainerMvhfkx6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPresentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._NWIuTN.App\Entity\Present' shared service.
     *
     * @return \App\Entity\Present
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._NWIuTN": it references class "App\\Entity\\Present" but no such service exists.');
    }
}
