<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMvhfkx6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMvhfkx6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMvhfkx6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMvhfkx6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMvhfkx6\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mvhfkx6',
    'container.build_id' => 'cf5307d1',
    'container.build_time' => 1634136905,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMvhfkx6');
