<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'acceuil' => [[], ['_controller' => 'App\\Controller\\AcceuilController::index'], [], [['text', '/']], [], []],
    'avis' => [[], ['_controller' => 'App\\Controller\\AvisController::index'], [], [['text', '/avis']], [], []],
    'avis_nouveau' => [[], ['_controller' => 'App\\Controller\\AvisController::createAvis'], [], [['text', '/avis/nouveau']], [], []],
    'avis_show' => [['id'], ['_controller' => 'App\\Controller\\AvisController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/avis']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], []],
    'presentation' => [[], ['_controller' => 'App\\Controller\\PresentationController::index'], [], [['text', '/presentation']], [], []],
    'presentation_new' => [[], ['_controller' => 'App\\Controller\\PresentationController::formPresentation'], [], [['text', '/presentation/new']], [], []],
    'presentation_edit' => [['id'], ['_controller' => 'App\\Controller\\PresentationController::formPresentation'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/presentation']], [], []],
    'presentation_delete' => [['id'], ['_controller' => 'App\\Controller\\PresentationController::deletePresentation'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/presentation']], [], []],
    'prestation' => [[], ['_controller' => 'App\\Controller\\PrestationController::index'], [], [['text', '/prestation']], [], []],
    'prestation_create' => [[], ['_controller' => 'App\\Controller\\PrestationController::form'], [], [['text', '/prestation/new']], [], []],
    'prestation_edit' => [['id'], ['_controller' => 'App\\Controller\\PrestationController::form'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/prestation']], [], []],
    'prestation_delete' => [['id'], ['_controller' => 'App\\Controller\\PrestationController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/prestation']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
